### ISSUE TITLE
[BUG] agent tries to connect over http when unix socket endpoint is enabled

### ISSUE THREAD

**Issue by pdeva** [DataDog/dd-trace-go#2658]
**Version of dd-trace-go**

1.62.0
**Describe what happened:**

in kubernetes, constantly seeing these errors for our golang services when tracing is enabled:
![Screenshot 2024-04-12 at 7 33 33 PM](https://github.com/DataDog/dd-trace-go/assets/3190176/367814b1-d61c-4114-8d92-e6b04acdc11d)

**Describe what you expected:**
while the apm functionality is still working for these services, this error shouldnt be present. it seems while its still sending traces over unix socket, the tracer is still trying to talk to the datadog agent over http port for some reason.

**Steps to reproduce the issue:**

this is how we init our tracer:

```go
import(
	"go.opentelemetry.io/otel"
	ddotel "gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentelemetry"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
	"gopkg.in/DataDog/dd-trace-go.v1/profiler"
)

func initTracer(cfg config.ServiceConfig) *ddotel.TracerProvider {
	if !cfg.IsLocalProfile() && !cfg.TracingDisabled {
		traceProvider := ddotel.NewTracerProvider(tracer.WithRuntimeMetrics())
		otel.SetTracerProvider(traceProvider)

		if config.ShouldProfile(cfg) {
			err := profiler.Start(
				profiler.WithService(cfg.ServiceName),
				profiler.WithVersion(cfg.ServiceVersion),
			)
			if err != nil {
				log.Fatal().Err(err)
			}
		}
		datastreams.Start()

		return traceProvider
	}

	return nil
}
```

here is the relevant config of the k8s deployment of each of the services:

```yaml


      volumeMounts:
        - mountPath: /var/run/datadog
          name: apmsocketpath

      volumes:
      - hostPath:
          path: /var/run/datadog/
        name: apmsocketpath


      - env:
        - name: DD_TRACE_AGENT_URL
          value: unix:///var/run/datadog/apm.socket
        - name: DD_TRACE_SAMPLE_RATE
          value: "1.0"
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
```

this is the relevant config of the datadog helm chart:

![Screenshot 2024-04-12 at 7 37 58 PM](https://github.com/DataDog/dd-trace-go/assets/3190176/7f8ed80a-0b0f-4b7c-bb1c-dda02cc28ff5)

**Additional environment details (Version of Go, Operating System, etc.):**
EKS 1.29
Go 1.22.1
