### ISSUE TITLE
dd-trace-go adds huge number of unnecessary dependencies and its own vendor folder

### ISSUE THREAD

**Issue by roustem** [DataDog/dd-trace-go#314]
We are trying to updated the vendored `dd-trace-go` library and noticed that the number of dependencies has grown dramatically -- over 50,000 new lines have been added.

AFAICT, many of the dependencies are not required. It would be great if the repository structure would allow us to vendor a smaller subset of the code.

**Comment by dd-caleb** [comment]
Indeed we have added a lot of new integrations over the last couple weeks. Are you using [github.com/golang/dep](https://github.com/golang/dep) to manage your dependencies?

If so, a `Gopkg.toml` file like this: (in this case only using the AWS integration)

```toml
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.10"

[[constraint]]
  name = "gopkg.in/DataDog/dd-trace-go.v1"
  version = "1.1.1"

[prune]
  go-tests = true
  unused-packages = true
```

Should prune out the unused dependencies.

Does that help?
